### ISSUE TITLE
neo-gui is crashing while resyncing from scratch around block, 1,170,000

### ISSUE THREAD

**Issue by mwherman2000** [CityOfZion/neo-gui-developer#44]
Once it fails, it's repeatable.  neo-gui will sync for a few blocks and then fails within a few seconds of starting.  I'm running neo-gui in the Visual Studio debugger.
Traceback
```
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
Exception thrown: 'System.NotSupportedException' in Neo.VM.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>neo-gui.exe</AppDomain><Exception><ExceptionType>System.InvalidOperationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Operation is not valid due to the current state of the object.</Message><StackTrace>   at Neo.VM.RandomAccessStack`1.Peek(Int32 index)
   at Neo.SmartContract.ApplicationEngine.CheckArraySize()
   at Neo.SmartContract.ApplicationEngine.Execute()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.VM.RandomAccessStack`1.Peek(Int32 index)
   at Neo.SmartContract.ApplicationEngine.CheckArraySize()
   at Neo.SmartContract.ApplicationEngine.Execute()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.InvalidOperationException' occurred in Neo.VM.dll
Operation is not valid due to the current state of the object.
```

**Comment by mwherman2000** [comment]
mwherman2000 - Today at 6:39 AM
@birmas C:\NEO\neo-gui-developer\packages\Neo.VM.2.0.3\lib\net461\Neo.VM.dll

**Comment by mwherman2000** [comment]
mwherman2000 - Today at 6:41 AM
No ...I went back to an older copy of the project.
@birmas C:\NEO\neo-gui-developer\packages\Neo.2.3.3\lib\net461\Neo.dll

**Comment by ghost** [comment]
Closing this after discussions in discord: end result is that we believe the Neo.VM being used didn't contain the latest opcode support that had been added to neo-vm
